use rusqlite::{Connection, Result, params};
use crate::models::{Setting, SettingValueType};

pub fn migrate(conn: &mut Connection) -> Result<()> {
    // Core.Log section
    let settings = vec![
        Setting {
            name: "LogPluginManager".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for the plugin manager".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnlineIdentity".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online identity services".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnlineSession".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online sessions".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogMemory".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for memory operations".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogPakFile".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for pak file operations".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogTemp".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for temporary operations".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogLinker".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for linker operations".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnline".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online subsystem".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnlineGame".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online game features".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogAnalytics".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for analytics".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogConfig".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for configuration operations".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogInteractiveProcess".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for interactive processes".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogInput".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for input operations".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnlineEntitlement".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online entitlements".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnlineEvents".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online events".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnlineFriend".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online friend systems".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnlinePresence".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online presence".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnlineTitleFile".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online title files".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "LogOnlineUser".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls logging for online user operations".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
        Setting {
            name: "Global".to_string(),
            section: "Core.Log".to_string(),
            description: "Controls global logging level".to_string(),
            value_type: SettingValueType::String,
            current_value: "off".to_string(),
            default_value: "off".to_string(),
            min_value: None,
            max_value: None,
            impact: "Debugging".to_string(),
        },
    ];

    // Insert settings into the database
    let tx = conn.transaction()?;
    
    for setting in settings {
        let possible_values = match &setting.value_type {
            SettingValueType::Enum(values) => Some(serde_json::to_string(values).unwrap_or_default()),
            _ => None,
        };

        let value_type_str = match setting.value_type {
            SettingValueType::Boolean => "Boolean",
            SettingValueType::Integer => "Integer",
            SettingValueType::Float => "Float",
            SettingValueType::String => "String",
            SettingValueType::Enum(_) => "Enum",
        };

        tx.execute(
            "INSERT OR REPLACE INTO settings 
             (name, section, description, value_type, default_value, min_value, max_value, impact, possible_values)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)",
            params![
                setting.name,
                setting.section,
                setting.description,
                value_type_str,
                setting.default_value,
                setting.min_value,
                setting.max_value,
                setting.impact,
                possible_values,
            ],
        )?;
    }

    tx.commit()?;
    Ok(())
}